# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.

# AndroidX package structure
android.useAndroidX=true

# Enables non-transitive R classes
android.nonTransitiveRClass=true

# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official

# JVM arguments for the Gradle daemon
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8

# Compose compiler extension version matching Kotlin 1.9.22
composeCompilerExtensionVersion=1.5.8
